services:

  midarr:
    container_name: midarr
    build: .
    ports:
      - 4000:4000
    volumes:
      - ./:/app
      - ./misc/movies:/movies
      - ./misc/series:/series
    environment:
      - APP_URL=http://midarr:4000
      - SETUP_ADMIN_EMAIL=admin@email.com
      - SETUP_ADMIN_NAME=admin
      - SETUP_ADMIN_PASSWORD=passwordpassword
      - RADARR_BASE_URL=http://radarr:7878
      - RADARR_API_KEY=d031e8c9b9df4b2fab311d1c3b3fa2c5
      - SONARR_BASE_URL=http://sonarr:8989
      - SONARR_API_KEY=1accda4476394bfcaddefe8c4fd77d4a
    command: bash -c "chmod u+x misc/entry-point-local.sh && ./misc/entry-point-local.sh"

  radarr:
    container_name: radarr
    image: linuxserver/radarr:version-4.1.0.6175
    ports:
      - 7878:7878
    volumes:
      - ./misc/radarr/config.xml:/config/config.xml
      - ./misc/movies:/movies
    environment:
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: "exit 0"

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:version-3.0.9.1549
    ports:
      - 8989:8989
    volumes:
      - ./misc/sonarr/config.xml:/config/config.xml
      - ./misc/series:/series
    environment:
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: "exit 0"