name: Release Candidate

on:
  push:
    tags:
      - 'v*.*.*-rc.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build tag push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/midarrlabs/midarr-server:${{ env.RELEASE_VERSION }}
          build-args: |
            "MIX_ENV=prod"
            "SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}"